package cifrest

import (
  "github.com/peter-mount/golib/rest"
  "log"
  "strings"
)

// TimetableScheduleHandler implements a REST endpoint which returns the
// requested schedule based on it's generated scheduleId
func (c *CIFRest) TimetableScheduleHandler( r *rest.Rest ) error {
  id := r.Var( "id" )

  row := c.dbService.QueryRow( "SELECT timetable.timetableSchedule( $1 ) AS json", id )

  var tt []uint8
  err := row.Scan( &tt )
  if err != nil {
    r.Status( 500 )
    log.Printf( "500:id:%s:%s", id, err )
    return err
  }

  // As the JSON is generated by postgreSQL then just write the raw string
  // to the result
  r.Status( 200 ).Reader( strings.NewReader( string(tt) ) )

  return nil
}
